[package]
name = "gui_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial-core = "0.4"
serial = "0.4"
slcan = "0.1.3"
serialport = "4.2.0"
clap = "3.1.6"
